//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompareTable
    {
        public int CompareID { get; set; }
        public int Compare_UserID { get; set; }
        public int ProductDetailID { get; set; }
    
        public virtual ProductDetailTable ProductDetailTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
