//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReviewTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerReviewTable()
        {
            this.CustomerReviewImageTables = new HashSet<CustomerReviewImageTable>();
        }
    
        public int CustomerReviewID { get; set; }
        public int ProductHeaderID { get; set; }
        public string CustomerReview { get; set; }
        public int StatusID { get; set; }
        public int CustomerRewiew_UserID { get; set; }
        public int OrderHeaderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReviewImageTable> CustomerReviewImageTables { get; set; }
        public virtual OrderHeaderTable OrderHeaderTable { get; set; }
        public virtual ProductHeaderTable ProductHeaderTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
