//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategoryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainCategoryTable()
        {
            this.SubCategoryTables = new HashSet<SubCategoryTable>();
        }
    
        public int Main_CategoryID { get; set; }
        public string Main_CategoryTitle { get; set; }
        public int CreatedBy_UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public int StatusID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategoryTable> SubCategoryTables { get; set; }
    }
}
