//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeaderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHeaderTable()
        {
            this.CustomerReviewTables = new HashSet<CustomerReviewTable>();
            this.OrderDetailTables = new HashSet<OrderDetailTable>();
            this.OrderPaymentTables = new HashSet<OrderPaymentTable>();
        }
    
        public int OrderHeaderID { get; set; }
        public int Customer_UserID { get; set; }
        public int ShippingFeelID { get; set; }
        public int UserAddressID { get; set; }
        public double TotalCost { get; set; }
        public double DiscountAmount { get; set; }
        public double TotalPayment { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public int OrderStatusID { get; set; }
        public int PaymentTypeID { get; set; }
        public string TransectionNo { get; set; }
        public Nullable<System.DateTime> TransectionDate { get; set; }
        public Nullable<System.TimeSpan> TranscetionTime { get; set; }
        public string PaymentReceiptSnapshot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReviewTable> CustomerReviewTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTable> OrderDetailTables { get; set; }
        public virtual OrderStatusTable OrderStatusTable { get; set; }
        public virtual PaymentTypeTable PaymentTypeTable { get; set; }
        public virtual ShippingFeelTable ShippingFeelTable { get; set; }
        public virtual UserAddressTable UserAddressTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPaymentTable> OrderPaymentTables { get; set; }
    }
}
