//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pro_EccomerceDbEntities : DbContext
    {
        public Pro_EccomerceDbEntities()
            : base("name=Pro_EccomerceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressTypeTable> AddressTypeTables { get; set; }
        public virtual DbSet<BankAccountTable> BankAccountTables { get; set; }
        public virtual DbSet<BrandTable> BrandTables { get; set; }
        public virtual DbSet<CartTable> CartTables { get; set; }
        public virtual DbSet<CityTable> CityTables { get; set; }
        public virtual DbSet<ColorTypeTable> ColorTypeTables { get; set; }
        public virtual DbSet<CompareTable> CompareTables { get; set; }
        public virtual DbSet<CountryTable> CountryTables { get; set; }
        public virtual DbSet<CustomerReviewImageTable> CustomerReviewImageTables { get; set; }
        public virtual DbSet<CustomerReviewTable> CustomerReviewTables { get; set; }
        public virtual DbSet<DiscountTable> DiscountTables { get; set; }
        public virtual DbSet<GenderTable> GenderTables { get; set; }
        public virtual DbSet<MainCategoryTable> MainCategoryTables { get; set; }
        public virtual DbSet<OrderDetailTable> OrderDetailTables { get; set; }
        public virtual DbSet<OrderHeaderTable> OrderHeaderTables { get; set; }
        public virtual DbSet<OrderPaymentTable> OrderPaymentTables { get; set; }
        public virtual DbSet<OrderStatusTable> OrderStatusTables { get; set; }
        public virtual DbSet<PaymentStatusTable> PaymentStatusTables { get; set; }
        public virtual DbSet<PaymentTypeTable> PaymentTypeTables { get; set; }
        public virtual DbSet<ProductDetailTable> ProductDetailTables { get; set; }
        public virtual DbSet<ProductFeatureTable> ProductFeatureTables { get; set; }
        public virtual DbSet<ProductHeaderTable> ProductHeaderTables { get; set; }
        public virtual DbSet<ProductTagTable> ProductTagTables { get; set; }
        public virtual DbSet<SeasonDiscountTable> SeasonDiscountTables { get; set; }
        public virtual DbSet<SeasonTable> SeasonTables { get; set; }
        public virtual DbSet<ShippingFeelTable> ShippingFeelTables { get; set; }
        public virtual DbSet<SizeLevelTable> SizeLevelTables { get; set; }
        public virtual DbSet<SizeTypeByLevelTable> SizeTypeByLevelTables { get; set; }
        public virtual DbSet<SizeTypeTable> SizeTypeTables { get; set; }
        public virtual DbSet<StatusTable> StatusTables { get; set; }
        public virtual DbSet<SubCategoryTable> SubCategoryTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TagTable> TagTables { get; set; }
        public virtual DbSet<UnitTable> UnitTables { get; set; }
        public virtual DbSet<UserAddressTable> UserAddressTables { get; set; }
        public virtual DbSet<UserStatusTable> UserStatusTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<UserTypeTable> UserTypeTables { get; set; }
        public virtual DbSet<WishListTable> WishListTables { get; set; }
    }
}
