//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHeaderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductHeaderTable()
        {
            this.CustomerReviewTables = new HashSet<CustomerReviewTable>();
            this.ProductFeatureTables = new HashSet<ProductFeatureTable>();
            this.ProductTagTables = new HashSet<ProductTagTable>();
            this.SeasonDiscountTables = new HashSet<SeasonDiscountTable>();
            this.WishListTables = new HashSet<WishListTable>();
        }
    
        public int ProductHeaderID { get; set; }
        public int Sub_CategoryID { get; set; }
        public string ProductTitle { get; set; }
        public int BrandID { get; set; }
        public int CreatedBy_UserID { get; set; }
        public int UpdatedBy_UserID { get; set; }
        public string Productinformation { get; set; }
        public string SKUCode { get; set; }
    
        public virtual BrandTable BrandTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReviewTable> CustomerReviewTables { get; set; }
        public virtual ProductDetailTable ProductDetailTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFeatureTable> ProductFeatureTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual UserTable UserTable1 { get; set; }
        public virtual UserTable UserTable2 { get; set; }
        public virtual UserTable UserTable3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTagTable> ProductTagTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonDiscountTable> SeasonDiscountTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishListTable> WishListTables { get; set; }
    }
}
