//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonDiscountTable
    {
        public int SeasonDiscountID { get; set; }
        public int ProductHeaderID { get; set; }
        public int Discount_Percent { get; set; }
        public int StatusID { get; set; }
        public int SeasonID { get; set; }
    
        public virtual ProductHeaderTable ProductHeaderTable { get; set; }
        public virtual SeasonTable SeasonTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
