//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabeseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAddressTable()
        {
            this.OrderHeaderTables = new HashSet<OrderHeaderTable>();
        }
    
        public int UserAddressID { get; set; }
        public int UserID { get; set; }
        public int AddressTypeID { get; set; }
        public string FulllAddressTypeID { get; set; }
        public int CityID { get; set; }
        public string PostalCode { get; set; }
        public string ContactNo { get; set; }
        public int StatusID { get; set; }
    
        public virtual AddressTypeTable AddressTypeTable { get; set; }
        public virtual CityTable CityTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeaderTable> OrderHeaderTables { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
