//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int CartID { get; set; }
        public int ProductDetailID { get; set; }
        public int Quantity { get; set; }
        public int DiscountID { get; set; }
        public string UniqueNo { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual DiscountTable DiscountTable { get; set; }
    }
}
