//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReviewImageTable
    {
        public int CustomerReviewImageID { get; set; }
        public int CustomerReviewID { get; set; }
        public string imagePath { get; set; }
        public int StatusID { get; set; }
    
        public virtual CustomerReviewTable CustomerReviewTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        public virtual StatusTable StatusTable1 { get; set; }
    }
}
