//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountTable()
        {
            this.CartTables = new HashSet<CartTable>();
            this.OrderDetailTables = new HashSet<OrderDetailTable>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountTitle { get; set; }
        public string CouponCode { get; set; }
        public string DiscountDescription { get; set; }
        public double Discount_Percent { get; set; }
        public int StatusID { get; set; }
        public int CreatedBy_UserID { get; set; }
        public int UpdateBy_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTable> CartTables { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTable> OrderDetailTables { get; set; }
    }
}
