//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTable
    {
        public int OrderDetailID { get; set; }
        public int OrderHeaderID { get; set; }
        public int ProductDetailID { get; set; }
        public double UnitPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> DiscountID { get; set; }
    
        public virtual DiscountTable DiscountTable { get; set; }
        public virtual OrderHeaderTable OrderHeaderTable { get; set; }
        public virtual ProductDetailTable ProductDetailTable { get; set; }
    }
}
