//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeTypeByLevelTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SizeTypeByLevelTable()
        {
            this.ProductDetailTables = new HashSet<ProductDetailTable>();
        }
    
        public int SizeTypeLevelID { get; set; }
        public int SizeTypeID { get; set; }
        public int SizeLevelID { get; set; }
        public string SizeLevelValue { get; set; }
        public int StatusID { get; set; }
        public int GenderID { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetailTable> ProductDetailTables { get; set; }
        public virtual SizeLevelTable SizeLevelTable { get; set; }
        public virtual SizeTypeTable SizeTypeTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
