//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryTable
    {
        public int Sub_CategoryID { get; set; }
        public int Main_CategoryID { get; set; }
        public string Sub_CategoryTitle { get; set; }
        public int CreatedBy_UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual MainCategoryTable MainCategoryTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
